#!/bin/bash

set -e -o pipefail

if [ $# -le 2 ]; then
  echo "usage: $(basename $0) POSTGRES_VERSION AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY"
  exit 1
fi

PGSQL_VERSION=$1
AWS_ACCESS_KEY_ID=$2
AWS_SECRET_ACCESS_KEY=$3

for stack in "cedar-14" "heroku-16" "heroku-16-build" "heroku-18" "heroku-18-build";
  do
    echo "Building for $stack"
    BASE_STACK=$(echo "$stack" | sed "s/-/:/1") # heroku-16-build -> heroku:16-build
    docker build -t postgresql-builder --build-arg BASE_STACK="heroku/$BASE_STACK" --build-arg STACK_FOLDER="$stack" .
    docker run -e "S3_BUCKET=ci-database-binary" \
    -e "POSTGRESQL_VERSION=$PGSQL_VERSION" \
    -e "AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID" \
    -e "AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY" \
    -a=stdout -a=stderr postgresql-builder
    echo "Finished $stack"
  done
