# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
    test:
        parameters:
            stack:
                type: string
            pg_version:
                type: string
        environment:
            STACK: << parameters.stack >>
            POSTGRESQL_VERSION: << parameters.pg_version >>
        docker:
            - image: cimg/base:stable
        steps:
            - setup_remote_docker:
                version: 20.10.11
            - checkout
            - run:
                  name: "Running test"
                  command: ./support/test.sh "${STACK}"

workflows:
    main:
        jobs:
            - test:
                  matrix:
                      parameters:
                          pg_version: ["9.6", "10", "11", "12", "13", "14"]
                          stack: [heroku-18, heroku-20, heroku-22]
            - test:
                  pg_version: ""
                  stack: heroku-22
            - test:
                  pg_version: "11.7"
                  stack: heroku-22
