name: ci-postgresql

on: push

jobs:
  test:
    strategy:
      matrix:
        stack: [heroku-22, heroku-24]
        pg_version: ["", "13", "14", "15", "16", "17"]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Run Test
      run: ./support/test.sh ${{ matrix.stack }}
      env:
        POSTGRESQL_VERSION: ${{ matrix.pg_version }}

  # dummy job to wait and block merge until all jobs have completed
  done:
    runs-on: ubuntu-latest

    needs: [test]

    steps:
      - run: echo done
        working-directory: /
